version: '3.8'

services:
  graphql-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: graphql-gateway:latest
    container_name: graphql-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Server Configuration
      - NODE_ENV=production
      - PORT=8080
      - LOG_LEVEL=warn
      - SERVICE_NAME=graphql-gateway
      - SERVICE_VERSION=1.0.0
      - CORS_ALLOWED_DOMAIN=localhost
      - ENABLE_GRAPHQL_PLAYGROUND=false
      - ENABLE_INTROSPECTION=false
      - ALLOWED_BATCHED_REQUESTS=false
      # GraphQL Configuration
      - ENABLE_GRAPHQL_PLAYGROUND=false
      - ENABLE_INTROSPECTION=false
      - ALLOWED_BATCHED_REQUESTS=false
      - PRODUCTS_SERVICE_TOKEN=123456789
      # Security Configuration
      - ENABLE_RATE_LIMIT=true
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
      # Apollo Armor Configuration
      - ENABLE_BLOCK_FIELD_SUGGESTION=true
      - BLOCK_FIELD_SUGGESTION_MASK=<[REDACTED]>
      - ENABLE_COST_LIMIT=true
      - COST_LIMIT_MAX_COST=10000
      - COST_LIMIT_OBJECT_COST=2
      - COST_LIMIT_SCALAR_COST=1
      - COST_LIMIT_DEPTH_COST_FACTOR=1.5
      - COST_LIMIT_IGNORE_INTROSPECTION=true
      - ENABLE_MAX_DEPTH=true
      - MAX_DEPTH_LIMIT=15
      - MAX_DEPTH_FLATTEN_FRAGMENTS=false
      - ENABLE_MAX_ALIASES=true
      - MAX_ALIASES_LIMIT=50
      - ENABLE_MAX_DIRECTIVES=true
      - MAX_DIRECTIVES_LIMIT=100
      - ENABLE_MAX_TOKENS=true
      - MAX_TOKENS_LIMIT=2000
      # OpenTelemetry Configuration
      - OPEN_TELEMETRY_SERVICE_NAMESPACE=graphql-gateway
      - ENABLE_OPEN_TELEMETRY_METRICS=true
      - ENABLE_OPEN_TELEMETRY_TRACES=true
      - OPEN_TELEMETRY_TRACES_HEADERS={}
      - OPEN_TELEMETRY_METRICS_HEADERS={}
      - OPEN_TELEMETRY_TRACES_ENDPOINT_URL=http://localhost:4318/v1/traces
      - OPEN_TELEMETRY_METRICS_ENDPOINT_URL=http://localhost:4318/v1/metrics
      - OPEN_TELEMETRY_SAMPLING_RATE=1.0
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - gateway-network
    # Limit container resources
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  gateway-network:
    driver: bridge